name: Build & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set version for branch
        if: "!startsWith(github.ref, 'refs/tags/v')"
        run: echo "version=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Build archive and app
        env:
          DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer
        run: |
          xcodebuild archive -project Pomenetes.xcodeproj -scheme Pomenetes -configuration Release -archivePath Pomenetes.xcarchive
          xcodebuild -exportArchive -archivePath Pomenetes.xcarchive -exportOptionsPlist export_options.plist -exportPath .
          zip -r "Pomenetes-${{ env.version }}.zip" "Pomenetes.app"

      - name: Upload build artifact (for debugging)
        uses: actions/upload-artifact@v3
        with:
          name: Pomenetes-app
          path: Pomenetes*.zip

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: Pomenetes-${{ env.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
