name: Build & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set version for branch
        if: "!startsWith(github.ref, 'refs/tags/v')"
        run: echo "version=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Select latest available Xcode (16.x)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build archive and app
        run: |
          xcodebuild archive -project Pomenetes.xcodeproj -scheme Pomenetes -configuration Release -archivePath Pomenetes.xcarchive ARCHS="arm64 x86_64" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive -archivePath Pomenetes.xcarchive -exportOptionsPlist export_options.plist -exportPath . CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          zip -r "Pomenetes-${{ env.version }}.zip" "Pomenetes.app"

      - name: Upload build artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: Pomenetes-app
          path: Pomenetes*.zip

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: Pomenetes-${{ env.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
